services:
  - type: web
    name: react-app
    env: docker
    docker:
      dockerfile: Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    numInstances: 1
    healthCheckPath: /
    autoDeploy: true